apiVersion: apps/v1
kind: Deployment
metadata:
  name: ct-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      projectName: ct-api
    
  template:
    metadata:
      labels:
        app: ct
        projectName: ct-api
    spec:
      containers:
        - name: ct-pod
          image: brunosilvagarciadocker/conversao-temperatura:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-ct
spec:
  selector:
    projectName: ct-api
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30000
  type: NodePort
